// <auto-generated />
using System;
using CA.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CA.Persistence.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20240429184751_add_orders_data")]
    partial class add_orders_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CA.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a510554-0de4-43cc-a4aa-1b0c7aecde92"),
                            Comment = "comment for order 1",
                            EmailAddress = "user1@example.com",
                            FirstName = "Michael",
                            LastName = "Wilson",
                            OrderNumber = "ORD-1",
                            TotalAmount = 402m,
                            UserName = "User1"
                        },
                        new
                        {
                            Id = new Guid("8c2a2a4f-0ec7-4497-96fb-364871bb5e2e"),
                            Comment = "comment for order 2",
                            EmailAddress = "user2@example.com",
                            FirstName = "Emma",
                            LastName = "Johnson",
                            OrderNumber = "ORD-2",
                            TotalAmount = 236m,
                            UserName = "User2"
                        },
                        new
                        {
                            Id = new Guid("8b0fef59-c999-4e4f-85e4-27bffc0feb5d"),
                            Comment = "comment for order 3",
                            EmailAddress = "user3@example.com",
                            FirstName = "Sophia",
                            LastName = "Taylor",
                            OrderNumber = "ORD-3",
                            TotalAmount = 595m,
                            UserName = "User3"
                        },
                        new
                        {
                            Id = new Guid("58448317-cb14-417b-af1a-3c2b3b4bacb7"),
                            Comment = "comment for order 4",
                            EmailAddress = "user4@example.com",
                            FirstName = "Amelia",
                            LastName = "Martinez",
                            OrderNumber = "ORD-4",
                            TotalAmount = 641m,
                            UserName = "User4"
                        },
                        new
                        {
                            Id = new Guid("0d451300-edbb-4ccf-86bd-b6efc5b06098"),
                            Comment = "comment for order 5",
                            EmailAddress = "user5@example.com",
                            FirstName = "Emma",
                            LastName = "Johnson",
                            OrderNumber = "ORD-5",
                            TotalAmount = 752m,
                            UserName = "User5"
                        },
                        new
                        {
                            Id = new Guid("0cfa8b6b-111e-48f5-9444-fb9db49b7483"),
                            Comment = "comment for order 6",
                            EmailAddress = "user6@example.com",
                            FirstName = "James",
                            LastName = "Smith",
                            OrderNumber = "ORD-6",
                            TotalAmount = 151m,
                            UserName = "User6"
                        });
                });

            modelBuilder.Entity("CA.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a510554-0de4-43cc-a4aa-1b0c7aecde92"),
                            Category = "Gaming Console",
                            Name = "PlayStation 5",
                            Price = 499.00m,
                            Summary = "The next generation console with powerful graphics and immersive gaming experience."
                        },
                        new
                        {
                            Id = new Guid("8c2a2a4f-0ec7-4497-96fb-364871bb5e2e"),
                            Category = "Gaming Console",
                            Name = "Xbox Series X",
                            Price = 499.00m,
                            Summary = "Experience incredible speed and power with the fastest, most powerful Xbox ever made."
                        },
                        new
                        {
                            Id = new Guid("8b0fef59-c999-4e4f-85e4-27bffc0feb5d"),
                            Category = "Graphics Card",
                            Name = "NVIDIA RTX 3080",
                            Price = 699.00m,
                            Summary = "Take your graphics to the next level with this high-performance graphics card."
                        },
                        new
                        {
                            Id = new Guid("58448317-cb14-417b-af1a-3c2b3b4bacb7"),
                            Category = "Gaming Peripherals",
                            Name = "Razer BlackWidow Keyboard",
                            Price = 149.00m,
                            Summary = "A mechanical keyboard with customizable Chroma RGB lighting for enhanced gaming performance."
                        },
                        new
                        {
                            Id = new Guid("0d451300-edbb-4ccf-86bd-b6efc5b06098"),
                            Category = "Gaming Peripherals",
                            Name = "Logitech G502 Gaming Mouse",
                            Price = 59.00m,
                            Summary = "A high-performance wired mouse with customizable buttons and RGB lighting for ultimate control."
                        },
                        new
                        {
                            Id = new Guid("0cfa8b6b-111e-48f5-9444-fb9db49b7483"),
                            Category = "Gaming Monitors",
                            Name = "Samsung Odyssey G9 Gaming Monitor",
                            Price = 1299.00m,
                            Summary = "Immerse yourself in the game with this curved monitor featuring a high refresh rate and stunning visuals."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
